# Generated by Django 2.2.5 on 2021-10-25 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20211025_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 25, 23, 52, 55, 793637)),
        ),
    ]
