# Generated by Django 3.2.8 on 2021-10-25 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20211025_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 25, 23, 57, 24, 594365)),
        ),
    ]
