# Generated by Django 3.2.8 on 2021-10-27 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20211027_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 27, 18, 37, 59, 484491)),
        ),
    ]
